### ISSUE TITLE
using the subtype selector for the activity stream is broken

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#10]
when i choose, say 'blogs', in the subtype dropdown in the main activity list i see that:
* the 'view more' button at the bottom of the list is not rendered at all (no pagination)
* an ajax error is triggered every time that i change the subtype selector

**Comment by hypeJunction** [comment]
I am leaning towards removing the global setting. There is probably a ton of side effects. Ajaxifying lists should be done on per-list basis to ensure that all the required JS is loaded etc.

**Comment by propertunist** [comment]
i didn't use a global setting on my site. i just added the auto_refresh parameter to all entity lists.

**Comment by propertunist** [comment]
this issue no longer occurs for me in 1.12.x elgg
