### ISSUE TITLE
use an ajax loader animation while new data is loaded

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#11]
sometimes the data can take several seconds to be updated on my site - it would be great to use an ajax loader animation (elgg's loader/spinner view) to inform the user that activity in process.

**Comment by hypeJunction** [comment]
You can add ```body.elgg-state-loading``` to your theme stylesheet. I use it across all of my plugins.

**Comment by propertunist** [comment]
ok, though i just did that and i am not seeing the loader animation when i click the loading button on the main site activity stream.
