### ISSUE TITLE
is event triggered when loading infinitely paginated list data?

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#13]
i need to trigger a jquery function when new list data is loaded after the user clicks a 'load more' button (infinite pagination) at the bottom of an elgg list. i have looked through the js code for hypelist and seen the various events, such as 'pageShown.hypeList'  - but when i attach code to them, none of them have been triggered after i click the 'show more' button. 
is there an event i can use for this purpose?
i also added a function against the click even of the button itself, but even that doesn't trigger.. 
so i am thinking that maybe i am already using the correct event, but the code isn't running for some other reason.

**Comment by hypeJunction** [comment]
Events are triggered on the hypeList object instance:

```js
    $('#my-list').hypeList();
    var instance = $list.data('hypeList');
    $(instance).on('newItemsFetched', function(e) {
	  // do something
    });
}

**Comment by hypeJunction** [comment]
You can use `$('.elgg-list').on('change', callback)` in the next release.

**Comment by propertunist** [comment]
oh ok, great. i did just download the new master version of the code and used your suggested method for newItemsFetched. the result was that i still couldn't get my code to run when click the 'more items' button, but it does now run when the list is auto-refreshed.
additionally i am now seeing that the 'load more' button often doesn't render at all, with no errors logged in the browers/console or server log. this occurs maybe about 60% of the time.

**Comment by hypeJunction** [comment]
Working fine on my install. Will see if I can replicate later.

**Comment by propertunist** [comment]
hmm.. actually, it seems that on my local installation, the event is being triggered correctly. i'm not sure how i got confused there. the other issue with the button not rendering is occurring most of the time on my live and remote test site, but is not occurring on my local site. i will open a new issue for that

**Comment by propertunist** [comment]
so i am back to this issue now that the others appear to be resolved. i'm not clear on why i thought this event triggering was working correctly on some occasions, but not on others.. there is a chance that i was just seeing the event being triggered on list refresh and thinking that the event triggered as a result of me pressing the 'load more' button.
in any case, what i am currently seeing is that the event triggers on refresh, but not when i click the 'load more' button.
you can see this on my activity page. the event is intended to trigger some jquery that shortens the description text of items in the river, replacing the full text with a truncated version and a link. if you load more items you will see that usually they are not truncated until a few seconds after the list is updated: https://www.ureka.org/activity?type=object&subtype=videolist_item

**Comment by propertunist** [comment]
oh ok - now i am seeing that the event appears to be triggering correctly. so i'm not sure why there is a kind of intermittent failure occurring. i am also seeing that my browser is locking up every so often while i have the page open. i will explore some more to see if i can learn where the problem is.

**Comment by propertunist** [comment]
i have now disabled the event handler on my live site to stop the browser from locking up.
