### ISSUE TITLE
RSS lists break when hype lists is enabled

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#14]
i just noticed that all my site's RSS lists are rendered as empty when this plugin is enabled. i don't know why yet. any idea?

**Comment by hypeJunction** [comment]
Probably need to verify the viewtype in the hook.

**Comment by propertunist** [comment]
yes, i figured it out :)
i have patched my version and it is fine now

**Comment by hypeJunction** [comment]
Feel free to make a pull request with the patch

**Comment by propertunist** [comment]
i would do but i am still unable to login to github remotely and i have a big pile of other tasks to complete before i even get to that one.
all i did was, in 'wrap list view hook' - wrapped the main code with the logic: 
```
        $view_input = preg_replace('[\W]', '', get_input('view', ''));
        if ($view_input != 'rss')
        {
     ....     
        }
       else
            return;
