### ISSUE TITLE
load more button is not rendering

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#15]
if i choose 'infinite' or 'default' in the admin options then on my live and remote test sites i see :
default: no 'load more' button is rendered or any pagination buttons
infinite: usually the same as default, but sometimes will render the 'load more' button
off: works as normal.

on my local server: 
default: produces realtime ajax pagination with a list of number buttons - which works fine
infinite: produces the 'load more' button - which generally works fine
off: works as normal

the main difference between my local and remote server is that my local one is running fedora 22 and the remote one is fedora 20..  it might be a while before i can upgrade the remote one to find out if that is relevant.

**Comment by propertunist** [comment]
having debugged this, i found that the value 'self.options.count' of the pagination initialisation function in hypeList.js is sometimes being set to 0, instead of the correct total size of the list - even though the value of 'data-count' in the container div does contain the correct integer value for the count of the list items.

**Comment by propertunist** [comment]
ah so this appears to have been caused by the line you gave me to add in to resolve the other issue with the event firing for list updates. this line was initialising hypelists with no data and thus no count, i'm not clear yet on why this is a problem: 
```
 $('.elgg-list-container > .elgg-list').hypeList();
```
the file that i call this from has a require at the start that references hypelists, so it should load after hypelists' JS files load, i think.

**Comment by hypeJunction** [comment]
You need a specific instance. Either do this ` $('.elgg-list-container > .elgg-list').eq(0).hypeList();`, or iterate through your array.

**Comment by propertunist** [comment]
oh ok, that appears to have worked, but now i have other problems ;)
