### ISSUE TITLE
this.options is undefined

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#16]
with the latest version of this plugin's code, i now see the error 'this.options is undefined' in the browser console (firefox) after clicking the infinite 'load more' button.
the reference points to the 'framework/lists/init.js' file.

**Comment by hypeJunction** [comment]
I can't confirm. Everything is working as expected on my end.

**Comment by beautylix** [comment]
Release 3.3.2 works on elgg 1.12, but the latest release can not work on elgg 1.12 and 2.0, please fix the bug mentioned by propertunist

**Comment by hypeJunction** [comment]
@beautylix I am happy to fix the bug if there is one. There is no bug, and it works fine in both 1.12 and 2.0. Make sure you downloaded and unzipped the files correctly, remove the previous version completely, and use the releases tab to download a compiled package.

**Comment by hypeJunction** [comment]
Oh, I see what's happening. The spinner module is not loaded at the time the list is rendered in some cases.
