### ISSUE TITLE
page loading is much slower now

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#17]
i notice that the 'lazyLoad' parameter now defaults to 0. i thought that this parameter was used to load n pages in advance, so that multiple pages are loaded in advance, making loads quicker after the initial load. but that doesn't really fit the 'lazy loading' pattern.
in any case, i set it to 1 to test the outcome because i noticed that the infinite scroll function is now much slower than it was in the previous version of the code i was testing... however, changing this to 1 didn't speed up the page loading after clicking the 'load more' button.
am i missing the intended purpose of lazyloading here?

**Comment by propertunist** [comment]
the loading is actually so slow now that it may even be slower than just loading a whole new page!

**Comment by beautylix** [comment]
I installed and set up as infinite mode, but when I click "show next 10" button, nothing happened, could you tell me how to configure the plugin? thanks a lot.

**Comment by propertunist** [comment]
i am finding that with the current version, the infinite loading is very slow - so maybe you just need to wait for it to load

**Comment by beautylix** [comment]
It just shows a button showing "show next 10", when I clicked and waited a long time, nothing happened, I do not know how to use it

**Comment by hypeJunction** [comment]
Nothing has changed in terms of how the list is loaded or displayed. Given your previous questions, I assume you have modified the JS, perhaps you should try removing all the modifications first. I have just tried it on another site, and it's instant with lazy loading. Also look into your page HTML, perhaps there is something weird that jQuery has hard time parsing. For best results, isolate your list into a separate view, register it for ajax, and change 'base_url' parameter of the list, that way you will not need to wait for the whole page to reload, and only one view will be loaded.

**Comment by hypeJunction** [comment]
Just tested on both 1.12 and 2.0 and I don't see anything performance issues. Perhaps the event handler you registered is doing something heavy. Post your code, so I can take a look.

**Comment by beautylix** [comment]
lazyload does not work, I mean, when I scroll to the bottom, I must click the button to load more, and what I want is to scroll infinitely, I set the lazyload : 10,, how to set correctly?

**Comment by hypeJunction** [comment]
@beautylix This is an issue tracker, not a chat room and not a support forum. If you have a problem, open a new issue, do not hijack threads that are unrelated to your problem.
Lazy loading is a background process that preloads the pages before the user clicks the Next button. This plugin does not offer auto scrolling: a) it's bad UX when you can't see the footer, b) this plugin works upwards and downwards when loading list items, so it would be extremely annoying the page kept jumping when scrolled upwards.

**Comment by propertunist** [comment]
all i have done to your code is changed the default value for lazyloading to 1, from 0. but either way that doesn't change the performance. 
i didn't realise that registering an ajax view would result in greater performance since i haven't actually looked in depth at your code to learn how the infinite page loading is handled. the infinite loading is instant on my local server, but slow on my remote server.
i would post my code, but i have commented out the event handler and the performance remains slow, so i don't have any code to post that is relevant to hypelists.

you can see a slow loading page here on my test site: https://test.ureka.org/reference/all?sort=created_d&timing=all&contain=all&status=all&limit=5&list_type=list

**Comment by hypeJunction** [comment]
Try disabling piwik and interconnected and see if that affects performance. My guess if you have the JS in the entity listing that fires before the items are appended to the page.

**Comment by hypeJunction** [comment]
Something is clogging up the request server side. It's taking 344ms for the server to respond, so I would look there. It doesn't seem like a client side issue.

**Comment by hypeJunction** [comment]
AJAX view will definitely speed things up. It currently loads an entire page HTML and parses out the list by it's id, so if you only have the list as a response, it will be much faster.

**Comment by propertunist** [comment]
to my knowledge, all of my code has previously worked ok with the infinite loading feature. i just disable piwik and that made no difference. i will dig around the server later then and see if i can identify the cause of the delay.
i'll look at switching to ajax too, thanks for the tip.

**Comment by propertunist** [comment]
hmm, the only issue i can see presently is that on my test site, the JS console shows:
a) an ajax error before i have even used the ajax 'load more' feature of hypelists.
b) 
```
TypeError: this.options is undefined
<anonymous>
 init.js:2
n.event.dispatch()
 jquery.min.js:7
n.event.add/r.handle()
 jquery.min.js:7
n.event.trigger()
 jquery.min.js:7
e.event.trigger()
 jquery-migrate.min.js:2
.trigger/<()
 jquery.min.js:7
.each()
 jquery.min.js:6
n.prototype.each()
 jquery.min.js:6
.trigger()
 jquery.min.js:7
hypeList.prototype.hideLoader()
 hypeList.js:661
hypeList.prototype.showPage/<()
 hypeList.js:347
hypeList.prototype.loadPage()
 hypeList.js:272
hypeList.prototype.showPage()
 hypeList.js:343
hypeList.prototype.goToPage()
 hypeList.js:306
$.fn.hypeList/<()
 hypeList.js:874
.each()
 jquery.min.js:6
n.prototype.each()
 jquery.min.js:6
$.fn.hypeList()
 hypeList.js:866
hypeListPagination.prototype<.goToPage()
 hypeList.js:851
hypeListPagination.prototype<.bindEvents/</<()
 hypeList.js:840
n.event.dispatch()
 jquery.min.js:7
n.event.add/r.handle()
 jquery.min.js:7
 init.js:2:486
```

**Comment by propertunist** [comment]
i have just tested using elgg_is_xhr() in my code for the page, rather than using an ajax view.. i think it works ok (locally).

**Comment by propertunist** [comment]
i just saw your response to the other issue and that you had put a fix into the code. i downloaded and tested your latest release and now the speed is back to 'very fast' :)
