### ISSUE TITLE
Javascript error in runtime of refreshing

### ISSUE THREAD

**Issue by Wouter0100** [hypeJunction/hypeLists#19]
While deploying a new Elgg 2.0.2 instance, we came across this issue. It seems like it's blocking the autoRefresh in hypeWall.

> hypeList.js:240 Uncaught TypeError: Cannot read property 'length' of undefined
hypeList.scrollToTop @ hypeList.js:240
hypeList.addFetchedItems @ hypeList.js:486
(anonymous function) @ hypeList.js:427
(anonymous function) @ jquery.js:2i @ jquery.js:2
j.fireWith @ jquery.js:2z @ jquery.js:4
(anonymous function) @ jquery.js:4

**Comment by hypeJunction** [comment]
This should be fixed in one of the latest releases.

**Comment by Wouter0100** [comment]
We're running 3.5.5 (Composer) where it isn't fixed yet..

**Comment by hypeJunction** [comment]
Ah, looks like I didn't tag a release. Will do that now.

**Comment by Wouter0100** [comment]
Awesome. Thanks.
