### ISSUE TITLE
list ids on fetched data differ from original page - so fetching fails

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#22]
i have been testing the latest version of this code in elgg 2.1.2 and noticed that the lists are not being auto-refreshed for me. having just tracked through the code, i eventually found that the data-list-id variable that is attached to a list container is different when fetched via ajax. this has the effect of no data being added to the existing list. i have dumped the contents of the page that is fetched via ajax and can see clearly that it's ID is different to the one attached to the list container on the calling page.
i haven't yet found out why this is occurring, but since i am not so familiar with the intended behavior, i thought to let you know now.

**Comment by propertunist** [comment]
looks to me like the problem is due to the URL being used to call the page via ajax contains parameters that are not present on the load of the original page, so the MD5 generated is different. however, that would mean that the plugin would always fail - which is confusing me because i have seen it working. i continue!

**Comment by propertunist** [comment]
i looked at this again today and the only thought i had as to how i could understand how this process is intended to work is that the correct list_id could be passed in to the page when it is rendered during the ajax call initiated by hypeLists - otherwise the ids will always be different and the process fails.
am i missing something here?

**Comment by propertunist** [comment]
ah, i see - that is how the process is intended to work.. so for some reason the id is not being used correctly when the page is fetched via ajax.

**Comment by propertunist** [comment]
so i have resolved this by adding the following to start.php:
```
	if (!$list_id)
	{
		$list_id = get_input('list_id');
		if (strlen($list_id) <> 32)
			$list_id = '';
	}
```
i'm not sure why this was needed since this plugin definitely did work in earlier versions.

**Comment by hypeJunction** [comment]
That's not going to work. There can be multiple lists on a page - each needs a unique id. There was a problem with limi and offset being present in URLs, but I fixed that in one of the recent releases.

**Comment by propertunist** [comment]
i thought that the get_input command would get the input from the ajax request URL, not the main browser address bar URL - meaning that each call to get_input would only retrieve the list-id from the specific ajax request for the specific list that is being refreshed. since there is no list-id specified in the main browser URL for the page i am testing, i can only think that my assertion here is correct. the list refreshes correctly now, with the code i added.

**Comment by hypeJunction** [comment]
Server-side does not care about list IDs. List IDs are used client side to parse out the specific part of the page that contains list items for the given list.

**Comment by propertunist** [comment]
the function:  hypelists_wrap_list_view_hook
in start.php creates a list_id from the URL being used if no list_id is passed in to it (the hook). this is being triggered during the initial page load (creating the first list_id that gets rendered into the browser as an attribute of the container div for the list) and also triggered on each refresh request sent via ajax. when the refresh request is sent via ajax, the output of the MD5 function that creates the list_id is not the same as the output of the MD5 function when it is run to create the list_id for the initially rendered page - with the result that the data is not correctly returned into the rendered page and the list never updates. this appears to be because the URLs differ.
looking at the URLs being used, i can see that the limit and offset are present in the URLs being sent for the refresh event, so maybe you didn't integrate that fix into the github repo?

**Comment by hypeJunction** [comment]
If your data source is different from the page URL, pass base_url with the
list options.

**Comment by hypeJunction** [comment]
Also I think I have removed the URL from the list ID logic, not sure if it
made it to the repo yet.

**Comment by propertunist** [comment]
to be clear, i am saying that the URL for the page is www.mysite.org/activity and the url being used to fetch the new items via ajax is www.mysite.org/activity/?limit=12&offset=0
so that sounds like the bug you mentioned that you fixed, right?
would adding the base_url effect this issue?

**Comment by hypeJunction** [comment]
I always add base_url due to odd logic in pagination.
