### ISSUE TITLE
API requires more than 1 member to be added when creating new rooms

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#24]
this is how the code is configured presently, but how is that of benefit? if i am a site admin i might want to create rooms for others to come and join when i don't have any members (except maybe for me) to put in them.
i vote that this function be changed to place no limit on the numbers of members required to create a new room (or at least reduce it to 1).

**Comment by hypeJunction** [comment]
Is this the right plugin?

**Comment by propertunist** [comment]
erm.. no.. too many windows open! sry
