### ISSUE TITLE
loading animation does not use the elgg spinner

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#26]
it would be helpful if every instance of a loading animation in elgg pointed to the same elgg spinner. hypeLists currently has it's own way of rendering a loading animation and it is not directly compatible with the elgg spinner since the elgg spinner is a pair of divs and the hypeList animation is an li element and a hyperlink.
ideally the default elgg spinner would be used.

**Comment by hypeJunction** [comment]
It uses default spinner. Not sure what you are referring to

**Comment by hypeJunction** [comment]
https://github.com/hypeJunction/hypeLists/blob/master/views/default/components/list/list.js

**Comment by propertunist** [comment]
oh, so i just found out i was using version 4.0.2. as i never installed 4.0.4. now i do see the spinner at the top of the page when my theme is disabled but my theme hasn't been changed to accommodate the animation being at the top of the page, rather than being within the 'load more' button.
