### ISSUE TITLE
Infinite scroll bug or as designed

### ISSUE THREAD

**Issue by Wouter0100** [hypeJunction/hypeLists#27]
How's the infinite scroll designed to work? As I imagine, and some outdated infinite scroll plugins work, the list is automatically extended/loaded when the user nears the end of the page. Currently a button is viewed when at the end of the page. Is this as designed or a bug? 

If it's as designed, I'll open a PR to add this feature.

**Comment by hypeJunction** [comment]
That's by design. I think it's extremely bad UX (that annoys me personally) when you can't reach the end of the page. If you want infinite scroll, you can just trigger button click whenever it's in viewport.

**Comment by Wouter0100** [comment]
Ah, okay. Many customers would like to have this feature, and in some cases there is no "end of the page" (or footer) because of this feature.

**Comment by hypeJunction** [comment]
Just add your own javascript module that listens to window scrolls and triggers a click when the button is in viewport.
