### ISSUE TITLE
Drag and drop of plugins not working when hypeList or hypeScraper is Activated!

### ISSUE THREAD

**Issue by DaveONchE** [hypeJunction/hypeLists#29]
When hypeList/hypeScraper is activated, drag and drop of plugins in admin settings stops working on elgg 2.2.2.

**Comment by merilturock** [comment]
it's problem with the hypescraper .. The hypelist is working fine but it does not render hypegallery images alone.

**Comment by gerard-kanters** [comment]
If you disable hypescraper and enable hypelist, you cannot drag and drop plugins in admin settings. Disabling hypelists will provide that feature again.

**Comment by hypeJunction** [comment]
It's a side effect of setting all lists to be ajaxified automatically by hypeLists. Don't have a quick solution aside from disabling the feature.

**Comment by merilturock** [comment]
@gerard-kanters This really fixed the issue thank you so much.

**Comment by hypeJunction** [comment]
Fixed by https://github.com/hypeJunction/hypeLists/commit/a874cdee98e04842eaa29b90be94130f2282de30
