### ISSUE TITLE
Groups pagination not working

### ISSUE THREAD

**Issue by nfortea** [hypeJunction/hypeLists#33]
Hi,
When I activate hypeList, groups pagination in /groups/subgroups/list/ stop working. It's show a spinner but there are no changes in website. 
Looking in navigator console, I saw a new petition in network tab with a 200 status by POST limit=10
offset=20. Can you help me?
Regards,

**Comment by hypeJunction** [comment]
The plugin is not guaranteed to work with all lists. I don't know what subgroups are and how they implement their listing.

**Comment by nfortea** [comment]
Ok. Thank you!

FYI The plugin that we use is https://github.com/AU-Landing-Project/au_subgroups

**Comment by hypeJunction** [comment]
You can override the views and follow the documentation to implement the list in a compatible way
