### ISSUE TITLE
Trouble initiating a list in an ajax view.

### ISSUE THREAD

**Issue by Daltonmedia** [hypeJunction/hypeLists#5]
Hey,
I'm playing with this for a few weeks now and I'm having trouble with pagination in an ajax view.
I have quite complicated dynamic query to make this list and it's in a view 'fetch' which I register trough ajax which gets it into my mother page. This works without a problem, but pagination just doesn't get loaded after my ajax view is fetched.
First I thought it would be the data_source url that wasn' right, but I'm pretty sure it is, it points to my view the way it should and gives the right url query parameters to make the list.

The AMD module is loaded on my page, and I don't get any js errors in my console.
When I check the lists rendered html it's perfecly wrapped into your elgg-list-container with the correct data-parameters.
It feels like the js function just isn't initiated. I tried initating it programmatically, but that doesn't help, unless I'm doing something wrong there.
Do you have any idea how I could solve this? I'm getting close to moving back to a non-ajax load :)

**Comment by hypeJunction** [comment]
Here is a working example that ajaxifies the list of group members in a widget:

```php

$entity = elgg_get_page_owner_entity();
$base_url = "groups/members/$entity->guid";

$dbprefix = elgg_get_config('dbprefix');
echo elgg_list_entities_from_relationship(array(
	'types' => 'user',
	'relationship' => 'member',
	'relationship_guid' => $entity->guid,
	'inverse_relationship' => true,
	'joins' => array("JOIN {$dbprefix}users_entity u ON e.guid=u.guid"),
	'order_by' => 'u.name ASC',
	'full_view' => false,
	'list_id' => "group-members-$entity->guid",
	'pagination' => true,
	'pagination_type' => 'default',
	'item_view' => 'groups/member',
	'base_url' => $base_url,
));

```

I can't tell what's wrong unless you post some code.

**Comment by Daltonmedia** [comment]
yep, sorry.
I've simplyfied the example.
I'm sure the base_url is correct, since it works 'non ajaxed' and I've setup a pagehandler for the view, just to use it as base_url and it's working perfectly.

I have a view calculating the list and rendering the list.
```php
$base_url = elgg_get_site_url()."mydir/pagehandlername/?name=value&name2=value2";
$result = elgg_solr_object_search(null, null, array(), $solr_params);
$list = $result['entities'];
echo elgg_view_entity_list($list, array(
        'count' => $result['count'],
        'offset' => get_input("offset", 0),
        'limit' => 10,
        'full_view' => false,
        'list_type' => 'list',
        'pagination' => true,
        'pagination_type' => 'default',
        'list_class' => 'myplugin_search_list',
        'base_url' => $base_url,
    ));
```
whenever i call this view with:
```php
elgg_view('myplugin/fetchview');
```
It loads up as expected, the right entities are shown and the pagination works as expected.
But when I use:
```javascript
$('.elgg-form-myform').live('submit', function(e) {
    e.preventDefault();
    elgg.get('ajax/view/myplugin/fetchview', {
    beforeSend: function(){
     $("#loader").show();
   },
   complete: function(){
     $("#loader").hide();
   },
  success: function (output) {
    $('.result').html(output);
  }
    });
});
```
my view gets loaded as expected as well, the right entities are shown, **but pagination is not**.
Though I see in the rendered html that the list is wrapped in the hypelist wrapper and the data-attributes are added, there is just no pagination rendered (also the default elgg pagination is not).

**Comment by hypeJunction** [comment]
You need to instantiate a new list after you have modified the DOM, that is
in your success callback, use $.hypeList. I believe it's documented in
readme.

**Comment by Daltonmedia** [comment]
Thank you, I already tried that before, but appearently the wrong way.
I was initiating my list (myplugin_search_list) while that wasn't what I needed to do, the word 'new' in your resonse was the key :)

I turned off pagination in my list view (was important), and I initiate a complete new list upon ajax success.
since I needed the data parameters submitted in my form I used (just for documentation):

```javascript
$('.my-list-classname').hypeList({
        baseUrl:'mydir/pagehandlername/?'+$form.serialize(), 
        //count:  //need to figure out how to get them in response
        offset: 0, 
        offsetKey: 'offset', 
        limit: 10,
        pagination: 'default',
        });
```
It's working perfecly now, apart from the count, since the count is calculated in the fetchview and the ajax call just throws back the complete html. I just need to find a way to give my the count back seperately so I can include it in the js function so that the pages are correct as well, but I'll figure that out.
Thanks a lot for the help, first steps in ajax land for me.

**Comment by hypeJunction** [comment]
If you know the count server side, just add it as data-count attribute to
.my-list-classname, and then use that value in your js with
$('.my-list-classname').data('count')

On Fri, May 29, 2015 at 1:17 PM, Dries <notifications@github.com> wrote:

> Thank you, I already tried that before, but appearently the wrong way.
> I was initiating my list (myplugin_search_list) while that wasn't what I
> needed to do, the word 'new' in your resonse was the key :)
>
> I turned off pagination in my list view (was important), and I initiate a
> complete new list upon ajax success.
> since I needed the data parameters submitted in my form I used (just for
> documentation):
>
> $('.my-list-classname').hypeList({
>         baseUrl:'mydir/pagehandlername/?'+$form.serialize(),
>         //count:  //need to figure out how to get them in response
>         offset: 0,
>         offsetKey: 'offset',
>         limit: 10,
>         pagination: 'default',
>         });
>
> It's working perfecly now, apart from the count, since the count is
> calculated in the fetchview and the ajax call just throws back the complete
> html. I just need to find a way to give my the count back seperately so I
> can include it in the js function so that the pages are correct as well,
> but I'll figure that out.
> Thanks a lot for the help, first steps in ajax land for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypeJunction/hypeLists/issues/5#issuecomment-106777417>
> .
>



-- 
*Ismayil Khayredinov*
hypeJunction
Elgg Development Services

  ismayil.khayredinov@gmail.com
  +420 724 384 468
  ismayil.khayredinov

*"Hope is a state of mind, not of the world. Hope, in this deep and
powerful sense, is not the same as joy that things are going well, or
willingness to invest in enterprises that are obviously heading for
success, but rather an ability to work for something because it is good"* -
Vaclav Havel

**Comment by Daltonmedia** [comment]
haha! Great, thank!
