### ISSUE TITLE
hypeList is not a function (intermittent JS loading errors)

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#7]
many times i am loading list pages and the javascript is failing with this console message:
```
TypeError: $(...).hypeList is not a function init.js:1:234
```
this occurs for about 35% of the page loads where hypelist is used on my test site, though so far i do not know exactly why.

**Comment by hypeJunction** [comment]
Do you have some custom script that calls $.fn.hypeList? Or does this happen to the generic wrapper? If so, could it be that AMD modules are timing out?

**Comment by propertunist** [comment]
i am not calling hypeList manually, no. i have just added the refresh variable to my site's lists generically and sometimes the error occurs, sometimes it doesn't.
i also have a similar problem with juho's 'tour' plugin. in his case, the JS is loaded asynchronously when a button is pressed in the UI.
i don't have much more info to offer on this at this point.

**Comment by propertunist** [comment]
i am looking at this again and notice that if i switch between different pages that both use hypeLists, then i will see this error on the first load of each page every time..
but when i refresh the page after the 1st page load of either page, the error does not occur.

**Comment by propertunist** [comment]
hmm.. actually this is not as clear as i thought, since actually sometimes the pages load correctly the first time.

**Comment by propertunist** [comment]
it seems this is an anonymous define error, as defined here: 
http://requirejs.org/docs/errors.html#mismatch

i'm looking in hypelist.js and notice that the definition structure is different to my own AMD JS files and that of the other ones i have seen in the elgg community. maybe that is the cause of this issue?

**Comment by hypeJunction** [comment]
I have moved the jQuery plugin out of the view system, and it seems to not be producing this error any more. Can you do some testing?

**Comment by propertunist** [comment]
great, ok - it looks fixed here. (though now i have some other issues!)
