### ISSUE TITLE
regular AJAX errors when navigating

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeLists#9]
sometimes when i click a navigation link on any page that uses hypelists, elgg produces an AJAX error message 'Unexpected error while performing an AJAX call. Maybe the connection to the server is lost.'
when i view the firefox console (network panel) i see that this is most likely occurring while the hypeList polling action is being processed.
ideally there would be no error message produced if the user is navigating to a new page during the hypeList AJAX updates.

**Comment by hypeJunction** [comment]
hypeList is not producing errors, they are from Elgg core JS.

**Comment by propertunist** [comment]
in what way does the elgg core JS need to change? has this been raised as a ticket in elgg core?

**Comment by hypeJunction** [comment]
elgg.ajax is responsible for displaying errors. I am not sure there is a need to change anything.

**Comment by propertunist** [comment]
the result here is that a red error box appears informing users of an AJAX error after about 50% of the times that i navigate to a new page while viewing a page that renders a list managed by hype lists. so from my perspective, this is a UI bug. the errors of this type need to be silent.
